/*
 * keys.h
 * Copyright (C) 2018 daktak <daktak@domo.ddns.net>
 *
 * Distributed under terms of the GPLV3 license.
 */
#pragma once
#ifndef KEYS_H
#define KEYS_H

// Keys used in all messages.
#define KEY_MESSAGE_TYPE 0

// Keys used in weather message.
#define KEY_MESSAGE_ID 1
#define KEY_CONDITION_CODE 2
#define KEY_TEMPERATURE 3
#define KEY_IS_DAYLIGHT 4

// Keys used in ticker message
#define KEY_TICKER 21
#define KEY_MESSAGE_ID1 23

// Keys in string message
#define KEY_STRING 29
#define KEY_MESSAGE_ID2 28
// Keys used in settings message.
#define MESSAGE_KEY_SHOW_SECONDS_HAND 5
#define MESSAGE_KEY_TEMPERATURE_UNITS 6
#define MESSAGE_KEY_VIBRATE_ON_BLUETOOTH_DISCONNECT 7
#define MESSAGE_KEY_SHOW_BATTERY_AT_PERCENT 8
#define MESSAGE_KEY_HAND_STYLE 9
#define MESSAGE_KEY_BG_COLOR 10
#define MESSAGE_KEY_FG1_COLOR 11
#define MESSAGE_KEY_FG2_COLOR 12
#define MESSAGE_KEY_FG3_COLOR 13
#define MESSAGE_KEY_TEMPERATURE_SIZE 14
#define MESSAGE_KEY_WEATHER_QUIET_TIME 15
#define MESSAGE_KEY_WEATHER_QUIET_TIME_START 16
#define MESSAGE_KEY_WEATHER_QUIET_TIME_STOP 17
#define MESSAGE_KEY_SECONDS_HAND_DURATION 18
#define MESSAGE_KEY_WEATHER_SOURCE 19
#define MESSAGE_KEY_SHOW_TIMEZONE 20
#define MESSAGE_KEY_TICKER_ON 26
#define MESSAGE_KEY_STRING_ON 27
#define MESSAGE_KEY_STRING_URL 30
#define MESSAGE_KEY_OPENWM_API 31

// Message types.
#define MESSAGE_TYPE_READY 0
#define MESSAGE_TYPE_WEATHER 1
#define MESSAGE_TYPE_SETTINGS 2
#define MESSAGE_TYPE_TICKER 3
#define MESSAGE_TYPE_STRING 4

// Temperature units.
#define TEMPERATURE_UNITS_CELSIUS 0
#define TEMPERATURE_UNITS_FAHRENHEIT 1

// Ticker settings
#define MESSAGE_KEY_COIN 24
#define MESSAGE_KEY_CURRENCY 25

// Weather sources  -- Yahoo stopped working for me as of 8/23/2016.  Appears to be a problem with converting lat/long to WOEID
#define WEATHER_SOURCE_OPENWEATHERMAP 1
#define WEATHER_SOURCE_YAHOO 2

// state of how to handle seconds hand  -- 0x08 mask means show seconds hand   0x04 means we need to be registerd for the tap sensor
#define SHOW_SECONDS_HAND(x)  (x & 0x8)
#define TAP_SENSOR_NEEDED(x)  (x & 0x4)
#define SECONDS_HAND_OFF 0x0                        // binary 0000 or 0
#define SECONDS_HAND_ON 0x8                         // binary 1000 or 8
#define SECONDS_HAND_FOR_FIXED_DURATION_OFF 0x5     // binary 0101 or 5
#define SECONDS_HAND_FOR_FIXED_DURATION_ON 0xd      // binary 1101 or 13
#define SECONDS_HAND_TOGGLE_TAP_OFF 0x6             // binary 0110 or 6
#define SECONDS_HAND_TOGGLE_TAP_ON 0xe              // binary 1110 or 15

// Condition codes.
// Reference: https://developer.yahoo.com/weather/documentation.html#codes
#define CONDITION_CODE_REFRESH -1
#define CONDITION_CODE_TORNADO 0
#define CONDITION_CODE_TROPICAL_STORM 1
#define CONDITION_CODE_HURRICANE 2
#define CONDITION_CODE_SEVERE_THUNDERSTORMS 3
#define CONDITION_CODE_THUNDERSTORMS 4
#define CONDITION_CODE_MIXED_RAIN_AND_SNOW 5
#define CONDITION_CODE_MIXED_RAIN_AND_SLEET 6
#define CONDITION_CODE_MIXED_SNOW_AND_SLEET 7
#define CONDITION_CODE_FREEZING_DRIZZLE 8
#define CONDITION_CODE_DRIZZLE 9
#define CONDITION_CODE_FREEZING_RAIN 10
#define CONDITION_CODE_SHOWERS 11
#define CONDITION_CODE_SHOWERS_ALIAS 12
#define CONDITION_CODE_SNOW_FLURRIES 13
#define CONDITION_CODE_LIGHT_SNOW_SHOWERS 14
#define CONDITION_CODE_BLOWING_SNOW 15
#define CONDITION_CODE_SNOW 16
#define CONDITION_CODE_HAIL 17
#define CONDITION_CODE_SLEET 18
#define CONDITION_CODE_DUST 19
#define CONDITION_CODE_FOGGY 20
#define CONDITION_CODE_HAZE 21
#define CONDITION_CODE_SMOKY 22
#define CONDITION_CODE_BLUSTERY 23
#define CONDITION_CODE_WINDY 24
#define CONDITION_CODE_COLD 25
#define CONDITION_CODE_CLOUDY 26
#define CONDITION_CODE_MOSTLY_CLOUDY_NIGHT 27
#define CONDITION_CODE_MOSTLY_CLOUDY_DAY 28
#define CONDITION_CODE_PARTLY_CLOUDY_NIGHT 29
#define CONDITION_CODE_PARTLY_CLOUDY_DAY 30
#define CONDITION_CODE_CLEAR_NIGHT 31
#define CONDITION_CODE_SUNNY 32
#define CONDITION_CODE_FAIR_NIGHT 33
#define CONDITION_CODE_FAIR_DAY 34
#define CONDITION_CODE_MIXED_RAIN_AND_HAIL 35
#define CONDITION_CODE_HOT 36
#define CONDITION_CODE_ISOLATED_THUNDERSTORMS 37
#define CONDITION_CODE_SCATTERED_THUNDERSTORMS 38
#define CONDITION_CODE_SCATTERED_THUNDERSTORMS_ALIAS 39
#define CONDITION_CODE_SCATTERED_SHOWERS 40
#define CONDITION_CODE_HEAVY_SNOW 41
#define CONDITION_CODE_SCATTERED_SNOW_SHOWERS 42
#define CONDITION_CODE_HEAVY_SNOW_ALIAS 43
#define CONDITION_CODE_PARTLY_CLOUDY 44
#define CONDITION_CODE_THUNDERSHOWERS 45
#define CONDITION_CODE_SNOW_SHOWERS 46
#define CONDITION_CODE_ISOLATED_THUNDERSHOWERS 47

// OpenWeatherMap condition codes:  http://openweathermap.org/weather-conditions
#define OWM_CONDITION_CODE_THUNDERSTORM_MIN 200
#define OWM_CONDITION_CODE_THUNDERSTORM_MAX 299
#define OWM_CONDITION_CODE_RAIN_MIN 300
#define OWM_CONDITION_CODE_RAIN_MAX 599
#define OWM_CONDITION_CODE_SNOW_MIN 600
#define OWM_CONDITION_CODE_LIGHT_RAIN_AND_SNOW 615
#define OWM_CONDITION_CODE_RAIN_AND_SNOW 616
#define OWM_CONDITION_CODE_SNOW_MAX 699
#define OWM_CONDITION_CODE_ATMOSPHERE_MIN 700
#define OWM_CONDITION_CODE_ATMOSPHERE_MAX 799
#define OWM_CONDITION_CODE_CLEAR 800
#define OWM_CONDITION_CODE_PARTLY_CLOUDY_MIN 801
#define OWM_CONDITION_CODE_PARTLY_CLOUDY_MAX 803
#define OWM_CONDITION_CODE_OVERCAST_CLOUDS 804
#define OWM_CONDITION_CODE_TORNADO 900
#define OWM_CONDITION_CODE_TROPICAL_STORM 901
#define OWM_CONDITION_CODE_HURRICANE 902
#define OWM_CONDITION_CODE_COLD 903
#define OWM_CONDITION_CODE_HOT 904
#define OWM_CONDITION_CODE_WINDY 905
#define OWM_CONDITION_CODE_HAIL 906

// Symbols available in the myicons-webfont.ttf
#define ICON_REFRESH "f"
#define ICON_TORNADO "A"
#define ICON_HURRICANE "B"
#define ICON_THUNDERSTORM "C"
#define ICON_FREEZING_RAIN "D"
#define ICON_RAIN "E"
#define ICON_SNOW "F"
#define ICON_FOG "G"
#define ICON_WINDY "H"
#define ICON_COLD "I"
#define ICON_CLOUDY "J"
#define ICON_PARTLY_CLOUDY_DAY "L"
#define ICON_PARTLY_CLOUDY_NIGHT "K"
#define ICON_CLEAR_DAY "N"
#define ICON_CLEAR_NIGHT "M"
#define ICON_HOT "O"
#define ICON_UNKNOWN "d"
#define ICON_NONE ""
#define ICON_RESTART "h"
#define ICON_CHARGING "s"
#define ICON_PLUGGED "t"
#define ICON_BLUETOOTH_DISCONNECT "b"

#endif /* !KEYS_H */
